### ISSUE TITLE
Minor issue in dimension formatting code

### ISSUE THREAD

**Issue by Moult** [kevancress/MeasureIt_ARCH#124]
I recently [stole this function](https://github.com/IfcOpenShell/IfcOpenShell/commit/f2de8ce8df38fc89dbcc3ddd4990ef4763145846) to get some basic imperial formatting in SVG: https://github.com/kevancress/MeasureIt_ARCH/blob/dcf607ce0896aa2284463c6b4ae9cd023fc54cbe/measureit_arch_geometry.py#L2905 (note to self: the license right now in the BlenderBIM Add-on is ambiguous - IfcOpenShell itself is LGPL, so...)

I think the indentation on L2991, 2996, 2997, 3002, 3003 is incorrect.

**Comment by kevancress** [comment]
Hey @Moult , sorry it took me a while to get to this, should be resolved in a1f3d67b7fa00e622cc13c68696f847ae0d989e8

I hadn't noticed that the odd indentation was causing issues until I re-implemented the hide units options for metric dimensions
