### ISSUE TITLE
Title image now wrong

### ISSUE THREAD

**Issue by globalcitizen** [kevancress/MeasureIt_ARCH#134]
It says "For Blender 2.8" but it actually should say "For Blender 2.8+" or just "For Blender" and then write specifics somewhere else so you don't have to update the damn graphic again 👍

**Comment by kevancress** [comment]
Fixed in 9f3f330f088ee7f1d2b72d57cee9dcc6db57e584.

Ps. I'm getting close to doing a proper wrap up for the version 0.4 stuff and then we can merge you pull request and just focus on the master branch! sorry its been taking me so long to get around to
