### ISSUE TITLE
Vertical text and items selection with viewport

### ISSUE THREAD

**Issue by irvnriir** [kevancress/MeasureIt_ARCH#144]
I didn't find a way to make it keep text (only) aligned to the camera rotation (to right, instead of up/down) .

And the feature why i look beyond the default Measureit, is an ability to delete the measurements trough any kind of selection in Viewport (for example selecting the primitives) . Because when there is 50+ of them, searching the lists is absurd . This feature seems to be missed here too .

**Comment by kevancress** [comment]
Hey @irvnriir 

Your right, MeasureIt-ARCH dimensions and annotations don't have a way to keep text aligned to the camera yet. I'm working on adding this to annotations soon.

For deleting dimensions: there's no way to delete them directly in the viewport. But using the dimension gizmo in the viewport will select that dimension in the list, so you don't have to search through them all! Here's a demo:
![selection demo](https://user-images.githubusercontent.com/16860574/98969906-55282a00-24dd-11eb-97f8-f9701a96bb6b.gif)

If it's not causing the dimension to be selected in the list, make sure you're using the latest version of the MeasureIt-ARCH master branch

**Comment by irvnriir** [comment]
@kevancress good to know, thanks . though i probably won't switch until Dimensions are aligned :)

**Comment by kevancress** [comment]
@irvnriir I'm closing this issue for now, I've added an options for Annotations to stay aligned to the camera view. It's in the development branch now.
