### ISSUE TITLE
"Dashed" endcaps are huge

### ISSUE THREAD

**Issue by mjepronk** [kevancress/MeasureIt_ARCH#157]
If I chose "Arrow Start" or "Arrow End": "Dashed", the end caps are out-of-proportion for the line.

I'll see if I can pick this up in the coming weeks, but anyway, I wanted to register the issue here.

**Comment by kevancress** [comment]
Ahh I thought I'd put a fix in for this a while ago but I must have forgotten to, This is a quick one so I'll take care of it today!

**Comment by mjepronk** [comment]
OK, cool!
