### ISSUE TITLE
View output path and date folder ignored

### ISSUE THREAD

**Issue by mjepronk** [kevancress/MeasureIt_ARCH#159]
Hi Kevan,
I've just noticed that we don't use the `output_path` and `date_folder` of the view anymore.
If you like I can create a PR, but how do we want the functionality to work?
In `render_main` and `render_main_svg`, if the current view (result of `get_view()`) has an `output_path` set, we use that one instead of `scene.render.filepath`?
Optionally, if `date_folder` is checked we add the date to the path?
I also saw `output_path` on schedules. I haven't used schedules yet, and am unsure what it is, but should we check that one too?

**Comment by kevancress** [comment]
Hey @mjepronk,

Actually, making a view active already sets scene.render.filepath to be the views output path.

It's in the update method in measureit_arch_views.py which gets called each time the viewContainers active index is changed.

Although setting it at render time like you're doing here is probably clearer / more efficient. Changing views can be pretty slow right now, and moving some things out of the update function like this might help speed things up!

I'll try and review and test this out this week!

**Comment by mjepronk** [comment]
Aah, OK, I missed the fact that it automatically updated... so I think this behavior is more intuitive.
Bonus is the speed and we don't mess with the users' render settings.
No worry, take your time.
