### ISSUE TITLE
v0.4.6: Python crash when doing MeasureIt_ARCH Image

### ISSUE THREAD

**Issue by ju1m** [kevancress/MeasureIt_ARCH#171]
Hi,
I've been playing (ie. clicking everywhere to see what's happening) for a few minutes with MeasureIt_ARCH v0.4.6 and hit a Python crash when clicking `MeasureIt_ARCH Image`, this is apparently due to a `dimesnion`/`dimension` typo, fixed in commit 7aefbe5b but which is not included in `mARCHv0.4.6`.
Thanks for this much needed plugin :)

**Comment by kevancress** [comment]
Hey @ju1m,

Thanks for the heads up, just fixed this in master 991563717772f140b6bef232e3c355e78644b8ac and updated the zip file on the release page, thanks!
