### ISSUE TITLE
Text boxes for MeasureIt

### ISSUE THREAD

**Issue by Melodicpinpon** [kevancress/MeasureIt_ARCH#175]
Good one, developpers,
MeasureIt is great to add labels; I use it to recreate an open source atlas of anatomy based on existing open source 3D files.

Since the text files are not linked to the objects and that the text objects are not facing the point of view outside of a camera; I'm stuck with this definition problem for now.

If I could use it to show the definition of the object inside the 3D view, my life would be a constant orgasm, so to say.

Thank you very much for your great work.
Two other thingies could be improved: make the labels/measures share colors as the objects do with the materials,
and allow to re-organize the labels.

I found out how to be able to move labels already done, or edit the mesh without messing with the labels, it's tricky but works.

**Comment by kevancress** [comment]
Hey @Melodicpinpon 

If you download the development branch of MeasureIt_ARCH there are some features that might help you out. Annotations have better multi line support, that allows for line re-ordering, and an option to keep annotations aligned to the camera view. If you use this along with the "lock camera to view" option in blenders view settings, your annotations should always face your viewport.

You can also attach annotations to an empty object, and then parent the empty to the geometry, if your planning on moving annotations around frequently.
