### ISSUE TITLE
Measurements Don't Render with no view plane set at certain angles (DIM PLACEMENT REFACTOR)

### ISSUE THREAD

**Issue by samucacsm** [kevancress/MeasureIt_ARCH#176]
![image](https://user-images.githubusercontent.com/39661545/117471155-f09ad480-af2d-11eb-87a8-a6ce1c77cafe.png)
Cant render measurements from a Ctrl-numpad 3 side view, only a numpad 3 side view. They appear normally on the viewport but when I hit the Render Image button they dont appear, only the contour lines.
I tried to delete the measurements and redo them, also tried to create a new camera, which worked on the numpad 3 side, but when moved to the other side, it simply wont render the measurements

**Comment by kevancress** [comment]
Hey @samucacsm

There was a bug in the 0.4.6 release that was causing some issues with the raster image rendering. I've just put up a fix for it on the release page. Give it a shot and let me know if that fixes things.

It also might be an issue with the dimension placement system, setting the view plane to the YZ Plane in your dimension settings might fix it?

**Comment by samucacsm** [comment]
thanks, I'm downloading it right now. 
One more thing, will line contours be available for instanced geometry nodes objects?

**Comment by samucacsm** [comment]
> Hey @samucacsm
> 
> There was a bug in the 0.4.6 release that was causing some issues with the raster image rendering. I've just put up a fix for it on the release page. Give it a shot and let me know if that fixes things.
> 
> It also might be an issue with the dimension placement system, setting the view plane to the YZ Plane in your dimension settings might fix it?

So, I downloaded it, and it wont render the measurements if i select none. I gotta select YZ so it renders

![image](https://user-images.githubusercontent.com/39661545/117747752-23babd80-b1e5-11eb-98ef-dbe82e612ebc.png)

**Comment by kevancress** [comment]
Ahh okay, yeah I'm working on a total refactor of the dimension placement/drawing system that should fix this in future updates, but it may be a while before I get that working.

Also, I did a couple test with geometry nodes and it does seem like linework is being instanced properly so far!!

**Comment by kevancress** [comment]
Took me a while but I think I've got this fixed in 7c6ee1b7c16f73f3e1b227673af894f99ff4df27
