### ISSUE TITLE
Add Multi Line Text & Custom Text for Dimension Elements

### ISSUE THREAD

**Issue by kevancress** [kevancress/MeasureIt_ARCH#65]

**Comment by meutzitzu** [comment]
Does this mean we can use Unicode like in FreeCAD where whenever I want to add a diameter dimension I just use the good'ol Ctrl+Shift+U, 2, 2, 0, 5  ( ∅ )

**Comment by kevancress** [comment]
Finally got a start on adding this in dc3a323b46ae3ad4d604ab4deb908bfc4c315728. Just a Single line off custom text that overrides  the default measurement as a start but I'll work on adding multi line, and prefix/suffix custom text too!

**Comment by kevancress** [comment]
Closing this, custom and multiline dim text is supported now!

@meutzitzu for some reason it won't let me type alt codes for special characters directly in blenders text boxes, but the do work if you copy and paste them in

![image](https://user-images.githubusercontent.com/16860574/118896280-d8d03280-b8d5-11eb-8feb-a107d61abd6d.png)
